// codegen/tests/bridge_test.cpp
//
// Value-ABI bridge ① (DESIGN.md §6a): the opaque C ABI dispatches to real
// numkit builtins by name, with box/unbox round-tripping scalars and arrays.
// Exercises the C ABI directly (the generated code will use it via the
// prelude RAII wrapper, brick ②).

#include "nk_codegen_rt.h"

#include "nk_codegen_test_paths.h"  // NK_SAMPLE_PLUGIN_PATH (generated by CMake)

#include <gtest/gtest.h>

#include <cmath>
#include <cstdio>

TEST(Bridge, ScalarBuiltin)
{
    nk_val x = nk_box_scalar(0.0);
    nk_val r = nk_call("sin", &x, 1, 1, nullptr, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 0.0);  // sin(0) = 0
    nk_release(x);
    nk_release(r);
}

TEST(Bridge, ScalarBuiltinNonzero)
{
    nk_val x = nk_box_scalar(1.0);
    nk_val r = nk_call("exp", &x, 1, 1, nullptr, nullptr);
    EXPECT_NEAR(nk_unbox_scalar(r), std::exp(1.0), 1e-12);
    nk_release(x);
    nk_release(r);
}

TEST(Bridge, ArrayBuiltinSum)
{
    const double in[3] = {1.0, 2.0, 3.0};
    nk_val       a     = nk_box_array(in, 3);
    EXPECT_EQ(nk_numel(a), 3u);
    nk_val r = nk_call("sum", &a, 1, 1, nullptr, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 6.0);
    nk_release(a);
    nk_release(r);
}

TEST(Bridge, ArrayBuiltinSortRoundTrip)
{
    const double in[4] = {3.0, 1.0, 4.0, 2.0};
    nk_val       a     = nk_box_array(in, 4);
    nk_val       s     = nk_call("sort", &a, 1, 1, nullptr, nullptr);
    ASSERT_EQ(nk_numel(s), 4u);
    double out[4] = {0, 0, 0, 0};
    nk_unbox_array(s, out, 4);
    EXPECT_DOUBLE_EQ(out[0], 1.0);
    EXPECT_DOUBLE_EQ(out[1], 2.0);
    EXPECT_DOUBLE_EQ(out[2], 3.0);
    EXPECT_DOUBLE_EQ(out[3], 4.0);
    nk_release(a);
    nk_release(s);
}

// CX4a: complex array box/unbox round-trip (interleaved re,im). Also drives a
// bridged complex builtin (fft) so a complex RESULT is unboxed via the new
// path. (The codegen complex bridge, CX4b, builds on these C-ABI primitives.)
TEST(Bridge, ComplexArrayRoundTrip)
{
    const double in[6] = {1, 2, 3, 4, 5, 6};  // 1+2i, 3+4i, 5+6i
    nk_val       a     = nk_box_complex_array(in, 3);
    ASSERT_NE(a, nullptr);
    ASSERT_EQ(nk_numel(a), 3u);
    double out[6] = {0, 0, 0, 0, 0, 0};
    nk_unbox_complex_array(a, out, 3);
    for (int i = 0; i < 6; ++i) EXPECT_DOUBLE_EQ(out[i], in[i]);  // exact round-trip
    nk_release(a);
}

TEST(Bridge, ComplexResultFromBridgedFft)
{
    // fft of a real signal returns a COMPLEX array; unbox via the complex path.
    const double sig[4] = {1.0, 2.0, 3.0, 4.0};
    nk_val       x      = nk_box_array(sig, 4);
    nk_val       y      = nk_call("fft", &x, 1, 1, nullptr, nullptr);
    ASSERT_NE(y, nullptr);
    ASSERT_EQ(nk_numel(y), 4u);
    double out[8] = {0};  // 4 complex
    nk_unbox_complex_array(y, out, 4);
    // DC bin = sum = 10 (imag 0); the transform is non-trivial elsewhere.
    EXPECT_DOUBLE_EQ(out[0], 10.0);
    EXPECT_DOUBLE_EQ(out[1], 0.0);
    nk_release(x);
    nk_release(y);
}

// A runtime error inside a bridged call must be TRANSLATED (nk_error),
// never thrown across the extern "C" boundary (that is UB). The call
// returns null and the process does not crash.
TEST(Bridge, ErrorTranslatedNotThrown)
{
    nk_val   x = nk_box_scalar(1.0);
    nk_error err;
    err.code = 0;
    nk_val r = nk_call("a_function_that_does_not_exist_zzz", &x, 1, 1, nullptr, &err);
    EXPECT_EQ(r, nullptr);            // failed cleanly
    EXPECT_NE(err.code, 0);           // error reported
    EXPECT_NE(err.message[0], '\0');  // with a message
    nk_release(x);
}

// Hardening (self-review): a null argument handle is REPORTED, never
// dereferenced (a null deref is UB the try/catch cannot save).
TEST(Bridge, NullArgHandleReportsError)
{
    nk_val   args[1] = {nullptr};
    nk_error err;
    err.code = 0;
    nk_val r = nk_call("sin", args, 1, 1, nullptr, &err);
    EXPECT_EQ(r, nullptr);
    EXPECT_NE(err.code, 0);
}

// Hardening (self-review): boxing a null array pointer fails cleanly; a
// zero-length array (null ok, nothing to read) is a valid empty handle.
TEST(Bridge, BoxArrayNullPointer)
{
    EXPECT_EQ(nk_box_array(nullptr, 3), nullptr);
    nk_val z = nk_box_array(nullptr, 0);
    EXPECT_EQ(nk_numel(z), 0u);
    nk_release(z);
}

// ---- A1: Dynamic-tier value operations (DESIGN.md §10 C1) ------------------
// The value-level operator + truthiness primitives the generated Dynamic tier
// (A2+) uses for operands whose type the codegen inference could not pin down.
// Overload-aware and identical to the interpreter (they route through the same
// Engine dispatch the TreeWalker / VM use).

TEST(Bridge, BinOpScalarArithmetic)
{
    nk_val a = nk_box_scalar(3.0);
    nk_val b = nk_box_scalar(4.0);
    nk_val s = nk_binop("+", a, b, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(s), 7.0);
    nk_val d = nk_binop("-", a, b, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(d), -1.0);
    nk_val p = nk_binop("*", a, b, nullptr);  // scalar "*" == mtimes
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(p), 12.0);
    nk_release(a);
    nk_release(b);
    nk_release(s);
    nk_release(d);
    nk_release(p);
}

TEST(Bridge, BinOpArrayElementwise)
{
    const double xa[3] = {1, 2, 3};
    const double xb[3] = {10, 20, 30};
    nk_val       a     = nk_box_array(xa, 3);
    nk_val       b     = nk_box_array(xb, 3);
    nk_val       s     = nk_binop(".*", a, b, nullptr);  // elementwise multiply
    ASSERT_EQ(nk_numel(s), 3u);
    double out[3] = {0, 0, 0};
    nk_unbox_array(s, out, 3);
    EXPECT_DOUBLE_EQ(out[0], 10.0);
    EXPECT_DOUBLE_EQ(out[1], 40.0);
    EXPECT_DOUBLE_EQ(out[2], 90.0);
    nk_release(a);
    nk_release(b);
    nk_release(s);
}

TEST(Bridge, BinOpComparisonIsLogical)
{
    nk_val a  = nk_box_scalar(3.0);
    nk_val b  = nk_box_scalar(4.0);
    nk_val lt = nk_binop("<", a, b, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(lt), 1.0);  // 3 < 4 -> true
    nk_val gt = nk_binop(">", a, b, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(gt), 0.0);
    nk_release(a);
    nk_release(b);
    nk_release(lt);
    nk_release(gt);
}

TEST(Bridge, UnOpNegateAndNot)
{
    nk_val a = nk_box_scalar(5.0);
    nk_val n = nk_unop("-", a, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(n), -5.0);
    nk_val z = nk_box_scalar(0.0);
    nk_val t = nk_unop("~", z, nullptr);  // ~0 -> true
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(t), 1.0);
    nk_release(a);
    nk_release(n);
    nk_release(z);
    nk_release(t);
}

TEST(Bridge, TruthScalarAndArray)
{
    nk_val t = nk_box_scalar(1.0);
    nk_val f = nk_box_scalar(0.0);
    EXPECT_EQ(nk_truth(t, nullptr), 1);
    EXPECT_EQ(nk_truth(f, nullptr), 0);
    nk_release(t);
    nk_release(f);
    const double allnz[3] = {1, 2, 3};
    const double hasz[3]  = {1, 0, 3};
    nk_val       a        = nk_box_array(allnz, 3);
    nk_val       z        = nk_box_array(hasz, 3);
    EXPECT_EQ(nk_truth(a, nullptr), 1);  // every element non-zero -> true
    EXPECT_EQ(nk_truth(z, nullptr), 0);  // a zero element -> false
    nk_release(a);
    nk_release(z);
}

// A numkit error in a value op (dimension mismatch) is TRANSLATED via nk_error,
// never thrown across the C boundary; the call returns null and is leak-free.
TEST(Bridge, BinOpErrorTranslatedNoLeak)
{
    const long long before = nk_debug_live_handles();
    const double     xa[2] = {1, 2};
    const double     xb[3] = {1, 2, 3};
    nk_val           a     = nk_box_array(xa, 2);
    nk_val           b     = nk_box_array(xb, 3);
    nk_error         err;
    err.code     = 0;
    nk_val r     = nk_binop("+", a, b, &err);  // incompatible dims
    EXPECT_EQ(r, nullptr);
    EXPECT_NE(err.code, 0);
    EXPECT_NE(err.message[0], '\0');
    nk_release(a);
    nk_release(b);
    EXPECT_EQ(nk_debug_live_handles(), before);  // no handle leaked on the error path
}

// nk_index resolves value(subs) the way the interpreter does — `value(subs)` is
// index/call-AMBIGUOUS, so an array is INDEXED but a function handle is CALLED.
// A Dynamic value thus behaves identically whatever it is at runtime (A4 soundness).
TEST(Bridge, IndexArrayElement)
{
    const double xa[4] = {10, 20, 30, 40};
    nk_val       a     = nk_box_array(xa, 4);
    nk_val       i     = nk_box_scalar(3.0);  // 1-based
    nk_val       r     = nk_index(a, &i, 1, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 30.0);  // a(3)
    nk_release(a);
    nk_release(i);
    nk_release(r);
}

TEST(Bridge, IndexFunctionHandleCalls)
{
    // value(subs) on a function handle is a CALL, not indexing — the crux of the
    // index/call ambiguity. sin(0) = 0 (NOT "element 0 of a handle").
    nk_val h = nk_eval("@sin", nullptr);
    ASSERT_NE(h, nullptr);
    nk_val arg = nk_box_scalar(0.0);
    nk_val r   = nk_index(h, &arg, 1, nullptr);
    ASSERT_NE(r, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 0.0);
    nk_release(h);
    nk_release(arg);
    nk_release(r);
}

TEST(Bridge, IndexVectorSubscriptSubArray)
{
    const double xa[4] = {10, 20, 30, 40};
    nk_val       a     = nk_box_array(xa, 4);
    const double ia[2] = {2, 4};
    nk_val       i     = nk_box_array(ia, 2);  // a([2 4]) -> [20 40]
    nk_val       r     = nk_index(a, &i, 1, nullptr);
    ASSERT_EQ(nk_numel(r), 2u);
    double out[2] = {0, 0};
    nk_unbox_array(r, out, 2);
    EXPECT_DOUBLE_EQ(out[0], 20.0);
    EXPECT_DOUBLE_EQ(out[1], 40.0);
    nk_release(a);
    nk_release(i);
    nk_release(r);
}

TEST(Bridge, IndexOutOfBoundsReported)
{
    const double xa[2] = {1, 2};
    nk_val       a     = nk_box_array(xa, 2);
    nk_val       i     = nk_box_scalar(5.0);  // out of bounds
    nk_error     err;
    err.code   = 0;
    nk_val r   = nk_index(a, &i, 1, &err);
    EXPECT_EQ(r, nullptr);
    EXPECT_NE(err.code, 0);  // bounds error translated, not UB
    nk_release(a);
    nk_release(i);
}

// Shape-preserving boxers for a Dynamic ARRAY operand (column-major). Round-trip
// box -> numel -> unbox (flat) confirms the shape + values survive.
TEST(Bridge, BoxMatrixRoundTrip)
{
    const double m[6] = {1, 4, 2, 5, 3, 6};  // 2x3, column-major
    nk_val       a    = nk_box_matrix(m, 2, 3);
    ASSERT_NE(a, nullptr);
    EXPECT_EQ(nk_numel(a), 6u);
    double out[6] = {0, 0, 0, 0, 0, 0};
    nk_unbox_array(a, out, 6);
    for (int i = 0; i < 6; ++i) EXPECT_DOUBLE_EQ(out[i], m[i]);
    nk_release(a);
}

TEST(Bridge, BoxArrayNdRoundTrip)
{
    const std::size_t dims[3] = {2, 2, 2};
    const double      v[8]    = {1, 2, 3, 4, 5, 6, 7, 8};  // 2x2x2, column-major
    nk_val            a       = nk_box_array_nd(v, dims, 3);
    ASSERT_NE(a, nullptr);
    EXPECT_EQ(nk_numel(a), 8u);
    double out[8] = {0, 0, 0, 0, 0, 0, 0, 0};
    nk_unbox_array(a, out, 8);
    for (int i = 0; i < 8; ++i) EXPECT_DOUBLE_EQ(out[i], v[i]);
    nk_release(a);
}

// ---- Plugin / extension ABI (DESIGN.md §6b) --------------------------------
// A plugin PROVIDES functions with the nk_fn signature (the mirror of
// nk_call). Once registered, they resolve from numkit source / nk_call /
// embedding exactly like a builtin — proving the register -> resolve ->
// dispatch loop with no core change (uses Engine::registerFunction).

// A plugin function: doubles its scalar argument.
static nk_val nk_test_double(const nk_val *args, size_t nargs, size_t nargout,
                             nk_val *extra_outs, nk_error *err)
{
    (void)nargs;
    (void)nargout;
    (void)extra_outs;
    (void)err;
    return nk_box_scalar(nk_unbox_scalar(args[0]) * 2.0);
}

TEST(Plugin, RegisterAndCall)
{
    ASSERT_EQ(nk_register_fn("nk_test_double", nk_test_double), 0);
    nk_val x = nk_box_scalar(21.0);
    nk_val r = nk_call("nk_test_double", &x, 1, 1, nullptr, nullptr);
    ASSERT_NE(r, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 42.0);
    nk_release(x);
    nk_release(r);
}

// A two-output plugin function: [q, r] = divmod(a, b).
static nk_val nk_test_divmod(const nk_val *args, size_t nargs, size_t nargout,
                             nk_val *extra_outs, nk_error *err)
{
    (void)nargs;
    (void)err;
    const double a = nk_unbox_scalar(args[0]);
    const double b = nk_unbox_scalar(args[1]);
    if (nargout >= 2 && extra_outs) extra_outs[0] = nk_box_scalar(std::fmod(a, b));
    return nk_box_scalar(std::trunc(a / b));  // quotient (first output)
}

TEST(Plugin, RegisterMultiOutput)
{
    ASSERT_EQ(nk_register_fn("nk_test_divmod", nk_test_divmod), 0);
    nk_val args[2] = {nk_box_scalar(17.0), nk_box_scalar(5.0)};
    nk_val extra[1] = {nullptr};
    nk_val q = nk_call("nk_test_divmod", args, 2, 2, extra, nullptr);
    ASSERT_NE(q, nullptr);
    ASSERT_NE(extra[0], nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(q), 3.0);         // 17 div 5
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(extra[0]), 2.0);  // 17 mod 5
    nk_release(args[0]);
    nk_release(args[1]);
    nk_release(q);
    nk_release(extra[0]);
}

// A plugin function that reports an error must surface as nk_error at the
// call site, never crash the process.
static nk_val nk_test_raise(const nk_val *args, size_t nargs, size_t nargout,
                            nk_val *extra_outs, nk_error *err)
{
    (void)args;
    (void)nargs;
    (void)nargout;
    (void)extra_outs;
    if (err) {
        err->code = 7;
        std::snprintf(err->message, sizeof(err->message), "plugin says no");
    }
    return nullptr;
}

TEST(Plugin, ErrorPropagates)
{
    ASSERT_EQ(nk_register_fn("nk_test_raise", nk_test_raise), 0);
    nk_val  x = nk_box_scalar(1.0);
    nk_error e;
    e.code = 0;
    nk_val r = nk_call("nk_test_raise", &x, 1, 1, nullptr, &e);
    EXPECT_EQ(r, nullptr);            // failed cleanly
    EXPECT_NE(e.code, 0);             // error reported across the bridge
    EXPECT_NE(e.message[0], '\0');    // with a message
    nk_release(x);
}

// Bad arguments to registration are rejected, not crashed.
TEST(Plugin, RegisterRejectsNull)
{
    EXPECT_NE(nk_register_fn(nullptr, nk_test_double), 0);
    EXPECT_NE(nk_register_fn("nk_test_null", nullptr), 0);
}

// The full loadable-plugin path: dlopen a standalone shared library, run its
// ABI-version check + registration hook, then call its registered function
// through the same dispatch as a builtin. This exercises the real plugin
// boundary end to end (no in-process shortcut).
TEST(Plugin, LoadSharedLibraryAndCall)
{
    nk_error err;
    err.code   = 0;
    const int rc = nk_load_plugin(NK_SAMPLE_PLUGIN_PATH, &err);
    ASSERT_EQ(rc, 0) << "load failed: " << err.message << " (path: " << NK_SAMPLE_PLUGIN_PATH << ")";

    nk_val x = nk_box_scalar(7.0);
    nk_val r = nk_call("nk_sample_triple", &x, 1, 1, nullptr, nullptr);
    ASSERT_NE(r, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 21.0);  // 7 * 3
    nk_release(x);
    nk_release(r);
}

// A missing / bad plugin path fails cleanly with an error, never crashes.
TEST(Plugin, LoadMissingFileFails)
{
    nk_error err;
    err.code     = 0;
    const int rc = nk_load_plugin("definitely_not_a_real_plugin_zzz.dll", &err);
    EXPECT_NE(rc, 0);
    EXPECT_NE(err.code, 0);
    EXPECT_NE(err.message[0], '\0');
}

// A valid DLL that exports no plugin entry points fails cleanly — exercising
// the FreeLibrary-on-failure path (the hardening fix): the just-loaded module
// is unmapped and an error is reported, no crash. (The runtime DLL itself is a
// real library but has no nk_plugin_register.)
TEST(Plugin, LoadNonPluginDllReportsMissingEntryPoints)
{
    nk_error err;
    err.code     = 0;
    const int rc = nk_load_plugin(NK_RT_SHARED_DLL, &err);
    EXPECT_NE(rc, 0);
    EXPECT_NE(err.code, 0);
    EXPECT_NE(err.message[0], '\0');
}

// ---- Embedding (DESIGN.md §6b) ---------------------------------------------
// nk_eval runs numkit source in the runtime's persistent workspace — the host
// embedding entry point.

TEST(Embed, EvalExpression)
{
    nk_error err;
    err.code = 0;
    nk_val r = nk_eval("3 + 4", &err);
    ASSERT_NE(r, nullptr) << err.message;
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 7.0);
    nk_release(r);
}

TEST(Embed, EvalStatefulWorkspace)
{
    nk_release(nk_eval("nk_embed_x = 10;", nullptr));  // persist into workspace
    nk_val r = nk_eval("nk_embed_x * 2", nullptr);
    ASSERT_NE(r, nullptr);
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 20.0);
    nk_release(r);
}

TEST(Embed, EvalArrayResult)
{
    nk_val r = nk_eval("sort([3 1 2])", nullptr);
    ASSERT_NE(r, nullptr);
    ASSERT_EQ(nk_numel(r), 3u);
    double out[3] = {0, 0, 0};
    nk_unbox_array(r, out, 3);
    EXPECT_DOUBLE_EQ(out[0], 1.0);
    EXPECT_DOUBLE_EQ(out[2], 3.0);
    nk_release(r);
}

TEST(Embed, EvalErrorTranslated)
{
    nk_error err;
    err.code = 0;
    nk_val r = nk_eval("error('boom from embed')", &err);
    EXPECT_EQ(r, nullptr);
    EXPECT_NE(err.code, 0);
    EXPECT_NE(err.message[0], '\0');
}

// A plugin function is callable from evaluated numkit source, not just nk_call
// — closing the loop: load a plugin, then USE it from a script.
TEST(Embed, EvalCallsPluginFunction)
{
    nk_error err;
    err.code = 0;
    ASSERT_EQ(nk_load_plugin(NK_SAMPLE_PLUGIN_PATH, &err), 0) << err.message;
    nk_val r = nk_eval("nk_sample_triple(5)", &err);
    ASSERT_NE(r, nullptr) << err.message;
    EXPECT_DOUBLE_EQ(nk_unbox_scalar(r), 15.0);  // 5 * 3
    nk_release(r);
}

// ---- handle-balance leak check (DESIGN.md §6a) -----------------------------
// Every box/call/eval result must be released; nk_debug_live_handles returns
// to baseline. The PORTABLE leak check for the bridge's own handle lifecycle
// (MSVC's ASan has no LeakSanitizer). Covers the multi-output extra-release
// path (a regression there would leave the counter > baseline) and errors.
TEST(Leak, HandleBalanceAcrossPaths)
{
    const long long base = nk_debug_live_handles();

    {  // box + release
        nk_val x = nk_box_scalar(2.0);
        nk_release(x);
    }
    {  // single-output call
        nk_val a = nk_box_scalar(0.0);
        nk_val r = nk_call("sin", &a, 1, 1, nullptr, nullptr);
        nk_release(a);
        nk_release(r);
    }
    {  // multi-output call — exercises the adapter's extra-output release path
        ASSERT_EQ(nk_register_fn("nk_bal_divmod", nk_test_divmod), 0);
        nk_val   args[2] = {nk_box_scalar(17.0), nk_box_scalar(5.0)};
        nk_val   extra[1] = {nullptr};
        nk_val   q        = nk_call("nk_bal_divmod", args, 2, 2, extra, nullptr);
        nk_release(args[0]);
        nk_release(args[1]);
        nk_release(q);
        nk_release(extra[0]);
    }
    {  // eval
        nk_val e = nk_eval("3 + 4", nullptr);
        nk_release(e);
    }
    {  // a failed call creates no net handle (release(null) is a no-op)
        nk_val   a = nk_box_scalar(1.0);
        nk_error err;
        err.code = 0;
        nk_val r = nk_call("a_fn_that_does_not_exist_zzz", &a, 1, 1, nullptr, &err);
        EXPECT_EQ(r, nullptr);
        nk_release(a);
        nk_release(r);
    }

    EXPECT_EQ(nk_debug_live_handles(), base) << "bridge leaked nk_val handles";
}
