// codegen/tests/tiered_test.cpp
//
// Codegen-as-plugin / tiered acceleration (DESIGN.md §6b): the capstone that
// ties the emitter, the AOT compiler, and the plugin loader together. It
// transpiles a scalar numkit function, wraps it as a plugin (emitScalarPlugin),
// COMPILES it to a shared library, LOADS it into the runtime (nk_load_plugin),
// calls it through the engine's dispatch (nk_call), and diffs the native
// result against the interpreter evaluating the same source.
//
// This is "a hot function runs native inside a live session". Skips cleanly
// when no external compiler is configured (toolchain-less CI stays green).

#include <numkit/codegen/aot.hpp>
#include <numkit/codegen/emitter.hpp>
#include <numkit/codegen/monomorphize.hpp>
#include <numkit/codegen/transfer.hpp>

#include <numkit/core/lexer.hpp>
#include <numkit/core/parser.hpp>

#include <numkit/bundle/standard_engine.hpp>
#include <numkit/core/engine.hpp>
#include <numkit/value/value.hpp>

#include "nk_codegen_rt.h"          // nk_box_scalar / nk_call / nk_load_plugin
#include "nk_codegen_test_paths.h"  // NK_BRIDGE_DIR (generated by CMake)

#include <gtest/gtest.h>

#include <filesystem>
#include <string>
#include <vector>

using numkit::ValueType;
using namespace numkit::codegen;

namespace {

// Find the single FUNCTION_DEF in a parsed program.
const numkit::ASTNode *onlyFunction(const numkit::ASTNode &root)
{
    for (const auto &c : root.children)
        if (c && c->type == numkit::NodeType::FUNCTION_DEF) return c.get();
    return nullptr;
}

}  // namespace

TEST(CodegenTiered, ScalarFunctionAsPluginMatchesInterpreter)
{
    if (!aot::available())
        GTEST_SKIP() << "no external compiler configured for this build";

    const char *src =
        "function y = nk_hot(a, b)\n"
        "  y = a*a + b*3;\n"
        "end\n";

    // 1. Parse + register transfers (incl. the user function itself).
    TransferRegistry reg;
    registerStandardTransfers(reg);
    numkit::Lexer  lex(src);
    numkit::Parser parser(lex.tokenize());
    auto           root = parser.parse();
    FunctionTable  table;
    collectFunctions(*root, table);
    registerUserFunctions(reg, table);
    const numkit::ASTNode *fn = onlyFunction(*root);
    ASSERT_NE(fn, nullptr);

    // 2. Emit the function wrapped as a plugin TU.
    const std::vector<ParamSpec> params = {
        {"a", InferredType::scalar(ValueType::DOUBLE)},
        {"b", InferredType::scalar(ValueType::DOUBLE)}};
    const std::string abiHeader = std::string(NK_BRIDGE_DIR) + "/nk_plugin.h";
    const std::string pluginSrc =
        emitScalarPlugin(*fn, params, reg, "nk_tiered_hot", abiHeader);

    // 3. Compile it to a shared library.
    auto base = std::filesystem::temp_directory_path() / "numkit_codegen_aot";
    std::filesystem::create_directories(base);
    const std::string lib = (base / "nk_tiered_hot.dll").string();
    const auto        cr  = aot::compileToSharedLibrary(pluginSrc, lib);
    ASSERT_EQ(cr.status, aot::CompileStatus::Ok)
        << "log:\n" << cr.log << "\n--- generated source ---\n" << pluginSrc;

    // 4. Load it into the runtime and call it through engine dispatch.
    nk_error err;
    err.code = 0;
    ASSERT_EQ(nk_load_plugin(lib.c_str(), &err), 0) << err.message;

    nk_val a    = nk_box_scalar(3.0);
    nk_val b    = nk_box_scalar(4.0);
    nk_val args[2] = {a, b};
    nk_val r    = nk_call("nk_tiered_hot", args, 2, 1, nullptr, &err);
    ASSERT_NE(r, nullptr) << err.message;
    const double got = nk_unbox_scalar(r);

    // 5. Reference: the interpreter evaluating the SAME source.
    numkit::StandardEngine engine;
    engine.eval(src);
    const double ref = engine.eval("nk_hot(3, 4)", true).toScalar();  // suppress display

    EXPECT_DOUBLE_EQ(got, ref);   // compiled plugin == interpreter
    EXPECT_DOUBLE_EQ(got, 21.0);  // 3*3 + 4*3

    nk_release(a);
    nk_release(b);
    nk_release(r);
}

// The explicit boundary: a non-scalar (array-valued) function is refused at
// emission, not mis-compiled.
TEST(CodegenTiered, RefusesNonScalarFunction)
{
    const char *src =
        "function y = nk_vec(v)\n"
        "  y = v * 2;\n"
        "end\n";

    TransferRegistry reg;
    registerStandardTransfers(reg);
    numkit::Lexer  lex(src);
    numkit::Parser parser(lex.tokenize());
    auto           root = parser.parse();
    FunctionTable  table;
    collectFunctions(*root, table);
    registerUserFunctions(reg, table);
    const numkit::ASTNode *fn = onlyFunction(*root);
    ASSERT_NE(fn, nullptr);

    // A row-vector parameter -> array output -> not a scalar plugin.
    const std::vector<ParamSpec> params = {
        {"v", InferredType::concrete(ValueType::DOUBLE, Shape::rowVector())}};
    const std::string abiHeader = std::string(NK_BRIDGE_DIR) + "/nk_plugin.h";
    EXPECT_THROW(emitScalarPlugin(*fn, params, reg, "nk_tiered_vec", abiHeader),
                 std::runtime_error);
}
