// runtime/tests/coder_test.cpp
//
// Regression guard for the AOT codegen + native-process builtins
// (coder / coder_run / system / runNative). `coder` (transpile) is pure C++
// and always runs; the other three spawn a native process and skip cleanly
// when no compiler / interpreter is configured (mirroring the codegen e2e
// tests' `aot::available()` gate), so a toolchain-less CI stays green.

#include <numkit/codegen/aot.hpp>
#include <numkit/core/engine.hpp>
#include <numkit/bundle/standard_engine.hpp>
#include <gtest/gtest.h>

#include <cstdlib>
#include <cstdio>
#include <string>

using namespace numkit;

class CoderTest : public ::testing::Test
{
public:
    StandardEngine engine;
    void SetUp() override { engine.eval("import compat.*;"); }
    Value eval(const std::string &c) { return engine.eval(c); }
    double evalScalar(const std::string &c) { return eval(c).toScalar(); }
    std::string evalString(const std::string &c) { return eval(c).toString(); }
};

// ── coder: transpile a nullary scalar function to C++ ───────────────────
TEST_F(CoderTest, TranspileScalarFunction)
{
    const std::string out = evalString(
        "v = coder('function y = f(); y = 3.14; end', 'f', '');");
    // The emitted TU is a self-contained C++ translation unit with the
    // RawBuffer ABI header and a `double f_1v()` definition.
    EXPECT_NE(out.find("Generated by numkit codegen"), std::string::npos);
    EXPECT_NE(out.find("double f_1v()"), std::string::npos);
}

// ── coder: accepts a double-quoted (STRING) source arg too ──────────────
TEST_F(CoderTest, AcceptsStringArg)
{
    const std::string out = evalString(
        "v = coder(\"function y = f(x); y = x * 2; end\", \"f\", \"double\");");
    // The emitted function takes a scalar double and returns one; the exact
    // mangled suffix (_1d / _1v / …) is the emitter's concern, not this test's,
    // so assert on the stable signature shape, not the specific symbol.
    EXPECT_NE(out.find("double f_"), std::string::npos);
    EXPECT_NE(out.find("(double x)"), std::string::npos);
    EXPECT_NE(out.find("x * 2.0"), std::string::npos);
}

// ── coder: bad argument type throws ─────────────────────────────────────
TEST_F(CoderTest, RejectsNonCharSource)
{
    EXPECT_ANY_THROW(eval("v = coder(42, 'f', '');"));
}

// ── coder_run: transpile + compile + run a nullary scalar function ──────
TEST_F(CoderTest, RunScalarFunction)
{
    if (!codegen::aot::available())
        GTEST_SKIP() << "no external compiler configured for this build";
    // The harness prints the scalar return with %.17g, so 3.14 rounds to
    // 3.1400000000000001 (the nearest double).
    const std::string out = evalString(
        "v = coder_run('function y = f(); y = 3.14; end', 'f', '');");
    EXPECT_NE(out.find("3.1400000000000001"), std::string::npos);
}

// ── coder_run: rejects a non-nullary entry (v1 limit) ───────────────────
TEST_F(CoderTest, RunRejectsArgs)
{
    if (!codegen::aot::available())
        GTEST_SKIP() << "no external compiler configured for this build";
    EXPECT_ANY_THROW(eval(
        "v = coder_run('function y = f(x); y = x*2; end', 'f', 'double');"));
}

// ── system: echo via the shell, two-output form ─────────────────────────
TEST_F(CoderTest, SystemEcho)
{
    // `echo` is available on Windows (cmd) and POSIX shells. The captured
    // output contains the echoed text; status is 0 on success.
    eval("[s, o] = system('echo nk_system_test');");
    EXPECT_NEAR(evalScalar("s"), 0.0, 1e-9);
    const std::string o = evalString("o");
    EXPECT_NE(o.find("nk_system_test"), std::string::npos);
}

// ── system: single-output returns the status, not cmdout ────────────────
TEST_F(CoderTest, SystemSingleOutputIsStatus)
{
    eval("s = system('echo nk_system_test');");
    EXPECT_NEAR(evalScalar("s"), 0.0, 1e-9);
}

// ── runNative: runs a .m via NUMKIT_INTERP, skips when unset ─────────────
TEST_F(CoderTest, RunNativeScript)
{
    if (const char *interp = std::getenv("NUMKIT_INTERP")) {
        if (interp[0] == '\0')
            GTEST_SKIP() << "NUMKIT_INTERP is set but empty";
    } else {
        GTEST_SKIP() << "NUMKIT_INTERP is not set — set it to the numkit exe "
                        "path to exercise runNative";
    }
    // The interpreter runs a trivial inline script written to a temp file.
    // Using the engine's own eval to build the script would be circular; a
    // fixed string is enough to confirm the spawn + capture path works.
    const char *src =
        "clear\nimport compat.*\nfprintf('nk_runnative_ok\\n')\n";
    char tmpPath[L_tmpnam];
    std::tmpnam(tmpPath);
    std::string path = std::string(tmpPath) + ".m";
    {
        std::FILE *f = std::fopen(path.c_str(), "wb");
        ASSERT_NE(f, nullptr);
        std::fputs(src, f);
        std::fclose(f);
    }
    const std::string expr =
        "[s, o] = runNative('" + path + "');";
    eval(expr);
    EXPECT_NEAR(evalScalar("s"), 0.0, 1e-9);
    const std::string o = evalString("o");
    EXPECT_NE(o.find("nk_runnative_ok"), std::string::npos);
    std::remove(path.c_str());
}

// ── runNative: throws when NUMKIT_INTERP is unset ───────────────────────
TEST_F(CoderTest, RunNativeThrowsWhenInterpUnset)
{
    // Only assert the unset-error path when NUMKIT_INTERP is genuinely unset
    // (the RunNativeScript test above may have set it). We temporarily clear
    // it via setenv('NUMKIT_INTERP','') — an empty value is treated as unset.
    eval("setenv('NUMKIT_INTERP', '');");
    EXPECT_ANY_THROW(eval("[s, o] = runNative('whatever.m');"));
}
