# cmake/gen_build_info.cmake
#
# Invoked via `cmake -P` with `-DOUT=<path>` to (re)generate a tiny
# header file containing the current wall-clock timestamp as a macro.
# The header is regenerated on every build (driven by a custom target
# in the top-level CMakeLists) so the `version` builtin reflects the
# actual LINK time of the binary, not the stale `__DATE__` macro from
# whenever library.cpp's translation unit happened to last compile.

string(TIMESTAMP TS "%Y-%m-%d %H:%M:%S" UTC)
get_filename_component(OUT_DIR "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUT_DIR}")
file(WRITE "${OUT}"
"#pragma once
// Auto-generated by cmake/gen_build_info.cmake — do not edit.
// Regenerated on every build via the numkit_build_info custom target.
#define NUMKIT_BUILD_TIMESTAMP \"${TS}\"

namespace numkit {
// Defined in libs/builtin/src/version_string.cpp.
const char *buildTimestamp();
}
"
)
