#!/usr/bin/env python3
"""
Rebuild PARITY_PROGRESS.md from MATLAB_PARITY_TODO.md + the existing
PROGRESS data (preserves any harness-recorded measurements).

Layout: one section per MATLAB-doc TODO section, with the namespace
in the heading. Each table covers every function from the TODO and
shows whatever measurement the harness has recorded for it (or empty
cells if it hasn't been benched yet).

Columns: function | status | numkit_ms | vs_MATLAB | vs_Octave |
correctness | comment

`matlab_ms` / `octave_ms` are intentionally dropped — only the ratios
remain (those are derived in the harness from internal raw timings).
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parent.parent.parent
TODO_MD = ROOT / "MATLAB_PARITY_TODO.md"
PROGRESS_MD = ROOT / "PARITY_PROGRESS.md"


# ───────────────────────────── data ──────────────────────────────────

@dataclass
class TodoEntry:
    name: str
    status: str   # "✅", "❌", "⚠️"
    notes: str    # comment column from TODO


@dataclass
class TodoSection:
    title: str          # full section heading text e.g. "Entering Commands"
    namespace: str      # extracted from **NS: ...**
    summary: str        # the "5 ✅ + 0 ⚠️ / 9 = 56%" string
    entries: List[TodoEntry] = field(default_factory=list)


@dataclass
class Measurement:
    """Per-function cells we want to keep in the new layout."""
    numkit_ms: str = ""
    vs_matlab: str = ""
    vs_octave: str = ""
    correctness: str = ""
    comment: str = ""


# ───────────────────────────── parsing ───────────────────────────────

SECTION_RX = re.compile(
    r"^###\s+(?P<title>.+?)\s+—\s+(?P<summary>.+?)\s+—\s+\*\*NS:\s*(?P<ns>.+?)\*\*\s*$"
)
ROW_RX = re.compile(r"^\|\s*`(?P<name>[^`]+)`\s*\|\s*(?P<status>[^|]+?)\s*\|\s*(?P<notes>[^|]*?)\s*\|\s*$")


def parse_todo(text: str) -> List[TodoSection]:
    sections: List[TodoSection] = []
    cur: TodoSection | None = None
    for line in text.splitlines():
        m = SECTION_RX.match(line)
        if m:
            cur = TodoSection(
                title=m.group("title").strip(),
                namespace=m.group("ns").strip(),
                summary=m.group("summary").strip(),
            )
            sections.append(cur)
            continue
        if cur is None:
            continue
        m = ROW_RX.match(line)
        if m:
            cur.entries.append(TodoEntry(
                name=m.group("name").strip(),
                status=m.group("status").strip(),
                notes=m.group("notes").strip(),
            ))
    return sections


# Old PROGRESS rows look like:
#   | `fn` | namespace | DONE | numkit_ms | matlab_ms | octave_ms | vs_MATLAB | vs_Octave | correctness | comment |
OLD_ROW_RX = re.compile(
    r"^\|\s*`(?P<name>[^`]+)`\s*\|"
    r"\s*(?P<ns>[^|]+?)\s*\|"
    r"\s*(?P<status>[^|]+?)\s*\|"
    r"\s*(?P<nk>[^|]+?)\s*\|"
    r"\s*(?P<ml>[^|]+?)\s*\|"
    r"\s*(?P<oc>[^|]+?)\s*\|"
    r"\s*(?P<vsM>[^|]+?)\s*\|"
    r"\s*(?P<vsO>[^|]+?)\s*\|"
    r"\s*(?P<corr>[^|]+?)\s*\|"
    r"\s*(?P<cmt>[^|]*?)\s*\|\s*$"
)
# New PROGRESS rows look like:
#   | `fn` | status | numkit_ms | vs_MATLAB | vs_Octave | correctness | comment |
NEW_ROW_RX = re.compile(
    r"^\|\s*`(?P<name>[^`]+)`\s*\|"
    r"\s*(?P<status>[^|]+?)\s*\|"
    r"\s*(?P<nk>[^|]+?)\s*\|"
    r"\s*(?P<vsM>[^|]+?)\s*\|"
    r"\s*(?P<vsO>[^|]+?)\s*\|"
    r"\s*(?P<corr>[^|]+?)\s*\|"
    r"\s*(?P<cmt>[^|]*?)\s*\|\s*$"
)


def parse_existing_progress(text: str) -> Dict[str, Measurement]:
    """Pick up the most recent measurement per function name from old or
    new format. Last occurrence wins (the journal is append-only)."""
    out: Dict[str, Measurement] = {}
    for line in text.splitlines():
        m = OLD_ROW_RX.match(line) or NEW_ROW_RX.match(line)
        if not m:
            continue
        # Skip the header-divider line (function == "function" looks the same
        # since we require backticks; can't actually match).
        out[m.group("name")] = Measurement(
            numkit_ms=m.group("nk").strip(),
            vs_matlab=m.group("vsM").strip(),
            vs_octave=m.group("vsO").strip(),
            correctness=m.group("corr").strip(),
            comment=m.group("cmt").strip(),
        )
    return out


# ─────────────────────────── rendering ───────────────────────────────

HEADER = """# numkit-m parity progress

Auto-generated by `tools/parity/run_parity.py` (per-function row updates) and
`tools/parity/regenerate_progress.py` (full rebuild from the TODO list).

This is the live parity map: every function from `MATLAB_PARITY_TODO.md`
gets a row here, organized by MATLAB-doc section + namespace. Empty cells
mean "not yet benched"; filled cells reflect the most recent harness run.

**Columns:**
- `function` — MATLAB-doc name
- `status` — ✅ implemented · ❌ missing · ⚠️ partial / operator-only
- `numkit_ms` — single-iteration mean (ms) on numkit native build
- `vs_MATLAB` — MATLAB_ms / numkit_ms (>1× = numkit faster)
- `vs_Octave` — same against Octave
- `correctness` — `OK` element-wise vs MATLAB · `MISMATCH` · `N/A` if
  the comparison engine doesn't support the function
- `comment` — input size / notes / deviations

"""

ROW_FMT = "| `{name}` | {status} | {numkit_ms} | {vs_matlab} | {vs_octave} | {correctness} | {comment} |"
HEAD_DIV = "| function | status | numkit_ms | vs_MATLAB | vs_Octave | correctness | comment |"
ALIGN_DIV = "|---|:---:|---:|---:|---:|:---:|---|"


def render(sections: List[TodoSection], measurements: Dict[str, Measurement]) -> str:
    lines = [HEADER.rstrip()]

    for sec in sections:
        # Section heading preserves TODO summary + namespace.
        lines.append("")
        lines.append(f"## {sec.title}")
        lines.append("")
        lines.append(f"**Namespace:** {sec.namespace} — {sec.summary}")
        lines.append("")
        lines.append(HEAD_DIV)
        lines.append(ALIGN_DIV)
        for e in sec.entries:
            mm = measurements.get(e.name, Measurement())
            # Use TODO comment as fallback when harness hasn't said anything.
            comment = mm.comment or e.notes
            lines.append(ROW_FMT.format(
                name=e.name,
                status=e.status,
                numkit_ms=mm.numkit_ms or "",
                vs_matlab=mm.vs_matlab or "",
                vs_octave=mm.vs_octave or "",
                correctness=mm.correctness or "",
                comment=comment,
            ))

    return "\n".join(lines) + "\n"


# ─────────────────────────────── main ────────────────────────────────

def main() -> int:
    todo_text = TODO_MD.read_text(encoding="utf-8")
    sections = parse_todo(todo_text)

    progress_text = PROGRESS_MD.read_text(encoding="utf-8") if PROGRESS_MD.exists() else ""
    measurements = parse_existing_progress(progress_text)

    out = render(sections, measurements)
    PROGRESS_MD.write_text(out, encoding="utf-8")

    n_total = sum(len(s.entries) for s in sections)
    n_with = sum(1 for s in sections for e in s.entries if e.name in measurements)
    print(f"Rebuilt {PROGRESS_MD.name}: {len(sections)} sections, "
          f"{n_total} functions, {n_with} with measurements.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
